name: Release

on:
  push:
    branches:
      - feat/*
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Install Ruby dependencies
        run: bundle install

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1.0"

      - name: Setup Certificates
        env:
          KEYCHAIN_PASSWORD: ${{ github.run_id }}
          DEVELOPMENT_CERTIFICATE_BASE64: ${{ secrets.DEVELOPMENT_CERTIFICATE }}
          DEVELOPMENT_P12_PASSWORD: ${{ secrets.DEVELOPMENT_CERTIFICATE_PWD }}
          DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          DISTRIBUTION_P12_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        run: |
          # create variables
          KEYCHAIN_PATH=$RUNNER_TEMP/signing.keychain-db
          DEV_CERT_PATH=$RUNNER_TEMP/development_certificate.p12
          DIST_CERT_PATH=$RUNNER_TEMP/distribution_certificate.p12
          PROFILE_PATH=$RUNNER_TEMP/profile.provisionprofile

          # import certificates from secrets
          echo -n "$DEVELOPMENT_CERTIFICATE_BASE64" | base64 --decode -o $DEV_CERT_PATH
          echo -n "$DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode -o $DIST_CERT_PATH
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PROFILE_PATH

          # create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Add development certificate and key to keychain (Certificate must be imported before the key)
          security import $DEV_CERT_PATH -P "$DEVELOPMENT_P12_PASSWORD" -T /usr/bin/codesign -k $KEYCHAIN_PATH
          security find-identity -p codesigning -v $KEYCHAIN_PATH

          # Add distribution certificate to keychain
          security import $DIST_CERT_PATH -P "$DISTRIBUTION_P12_PASSWORD" -T /usr/bin/codesign -k $KEYCHAIN_PATH
          security find-identity -p codesigning -v $KEYCHAIN_PATH

          # Set keychain as default and update search list
          security list-keychains -d user -s $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH

          # Set partition list for keychain
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Clean up certificate files
          rm $DEV_CERT_PATH $DIST_CERT_PATH

          # Export keychain path for later steps
          echo "GITHUB_KEYCHAIN_PATH=$KEYCHAIN_PATH" >> $GITHUB_ENV

          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install CocoaPods
        run: |
          cd macos
          pod install

      - name: Archive
        run: |
          cd macos 

          # Clear derived data
          rm -rf ~/Library/Developer/Xcode/DerivedData

          xcodebuild -workspace GitBar.xcworkspace -scheme GitBar -configuration Release clean archive -archivePath GitBar.xcarchive | xcpretty

      - name: Export App
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          PROVISIONING_PROFILE_NAME: ${{ secrets.PROVISIONING_PROFILE_NAME }}
        run: |
          cd macos
          security find-identity -v 
          xcodebuild -exportArchive -archivePath GitBar.xcarchive -exportPath Export -exportOptionsPlist ExportOptions.plist | xcpretty

          cd Export
          pwd
          ls -la

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GitBar-builds
          path: |
            macos/Export/*

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GitBar-builds
          path: |
            macos/GitBar.pkg

      # - name: Generate Changelog
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref_name }}

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     # body: ${{ steps.changelog.outputs.changes }}
      #     files: |
      #       macos/Export/GitBar.pkg
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
